### PR TITLE
fix: re-compile data for 1.0.30000909

### PR DESCRIPTION
**Pull request by keithamus**
I'm not really sure how this happened - but it looks like the last update to `caniuse-lite` did not quite update correctly.

Specifically, I noticed this because `caniuse-db` now marks Edge 18 as the latest version:

```bash
$ npm i caniuse-db@1.0.30000909
$ jq .agents.edge.current_version < node_modules/caniuse-db/fulldata-json/data-2.0.json
"18"
$ jq .agents.edge.version_list[6] < node_modules/caniuse-db/fulldata-json/data-2.0.json                                                                
{
  "version": "18",
  "global_usage": 0,
  "release_date": 1542067200,
  "era": 0,
  "prefix": ""
}
```

However caniuse-lite did not:

```bash
$ npm i caniuse-lite@1.0.30000909
$ node -p "require('caniuse-lite').agents.edge.release_date"                                                                                           
{ '12': 1438128000,
  '13': 1447286400,
  '14': 1470096000,
  '15': 1491868800,
  '16': 1508198400,
  '17': 1525046400,
  '18': null }
```

To produce this PR I did the following:

```bash
$ npm i caniuse-db@1.0.30000908
$ node publish.js
```

FWIW if you do the following:

```bash
$ git checkout master
$ npm t
```

You'll notice there are test failures because the tests verify `caniuse-lite` code against the `caniuse-db` data - you can see one of the tests that fails is around Edge 18. Checking out this PR though, you can see all tests pass.

### CODE REVIEW

**Comment by keithamus** [comment]
I'll close this as the 1.0.30000910 release fixes this issue.

**Comment by ai** [comment]
I will look at this weekend

**Comment by ai** [comment]
Yeap, we can't just fix JSON. We need to check scripts, which convert JSON from `caniuse-db`

**Comment by ai** [comment]
I checked repo. Have no idea what happened. Let’s wait for next `caniuse-db` release.

**Comment by ai** [comment]
The issue was fixed in latest release

**Pull request closed without merging**
